FROM __BASEIMAGE_ARCH__/golang:1.12.1-alpine3.9

__CROSS_COPY qemu/qemu-__QEMU_ARCH__-static /usr/bin/


WORKDIR /go/src/app
RUN apk add --no-cache git
RUN go get github.com/nats-io/go-nats-streaming
RUN apk del git
COPY . .
# RUN go build main.go
CMD [ "go", "run", "./main.go" ]
