apiVersion: "nats.io/v1alpha2"
kind: "NatsCluster"
metadata:
  name: "fogoh-nats"
spec:
  size: 1
---
apiVersion: "streaming.nats.io/v1alpha1"
kind: "NatsStreamingCluster"
metadata:
  name: "fogoh-streaming-nats"
spec:
  size: 1
  natsSvc: "fogoh-nats"