apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-rtmp
  labels:
    app: nginx-rtmp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-rtmp
  template:
    metadata:
      labels:
        app: nginx-rtmp
    spec:
      containers:
      - name: nginx-rtmp
        image: dvdgiessen/nginx-rtmp-docker:latest # https://github.com/DvdGiessen/nginx-rtmp-docker
        ports:
        - containerPort: 1935
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-rtmp
  labels:
    app: nginx-rtmp
spec:
  type: NodePort
  ports:
    - port: 1935
      protocol: TCP
      targetPort: 1935
      nodePort: 31113
  selector:
    app: nginx-rtmp