apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-rtmp
  labels:
    app: nginx-rtmp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-rtmp
  template:
    metadata:
      labels:
        app: nginx-rtmp
    spec:
      containers:
      - name: nginx-rtmp
        image: alfg/nginx-rtmp:latest # https://github.com/alfg/docker-nginx-rtmp
        ports:
        - containerPort: 1935
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-rtmp
  labels:
    app: nginx-rtmp
spec:
  type: NodePort
  ports:
    - name: rtmp
      port: 1935
      protocol: TCP
      targetPort: 1935
      nodePort: 31113
    - name: hls
      port: 8080
      targetPort: 80
      nodePort: 31119
  selector:
    app: nginx-rtmp