apiVersion: apps/v1
kind: Deployment
metadata:
  name: object-recognition
  labels:
    app: object-recognition
spec:
  replicas: 1
  selector:
    matchLabels:
      app: object-recognition
  template:
    metadata:
      labels:
        app: object-recognition
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: machinetype
                operator: In
                values:
                - intelfog
      containers:
      - name: object-recognition
        image: adikabintang/fogoh-obj-recognition:latest
        env:
        - name: NATS_ENDPOINT
          value: "nats://fogoh-nats:4222/" # TODO: nats svc
        - name: NATS_CLUSTER_NAME
          value: "fogoh-streaming-nats"
        - name: NATS_CLIENT_ID
          valueFrom:
            fieldRef:
              fieldPath: metadata.name # pod name
