apiVersion: apps/v1
kind: Deployment
metadata:
  name: raw-video-publisher
  labels:
    app: raw-video-publisher
spec:
  replicas: 1
  selector:
    matchLabels:
      app: raw-video-publisher
  template:
    metadata:
      labels:
        app: raw-video-publisher
    spec:
      containers:
      - name: raw-video-publisher
        image: adikabintang/fogoh-raw-vid-pub-go:latest
        ports:
        - containerPort: 3000
        env:
        - name: NATS_ENDPOINT
          value: "nats://fogoh-nats:4222/" # TODO: nats svc
        - name: NATS_CLUSTER_NAME
          value: "fogoh-nats"
        - name: NATS_CLIENT_ID
          value: "raw_publisher_1"
---
apiVersion: v1
kind: Service
metadata:
  name: raw-video-publisher
  labels:
    app: raw-video-publisher
spec:
  type: NodePort
  ports:
    - port: 3000
      protocol: TCP
      targetPort: 3000
      #nodePort: 31113
  selector:
    app: raw-video-publisher